<%@ page import="java.lang.*" %>
<%@ page import="java.sql.*" %>
<%@ page import="myPackage.DatabaseClass" %>
<%@ page import="java.io.*" %>
<%@ page contentType="application/vnd.ms-excel" %>
<%
    // Set content type for Excel
    response.setContentType("application/vnd.ms-excel");
    response.setHeader("Content-Disposition", "attachment;filename=exam_register.xls");
    
    // Check if user is admin/lecturer
    if (session.getAttribute("userId") == null) {
        response.sendRedirect("login.jsp");
        return;
    }
    
    myPackage.DatabaseClass pDAO = myPackage.DatabaseClass.getInstance();
    
    // Get parameters
    int examId = 0;
    String examIdParam = request.getParameter("exam_id");
    if (examIdParam != null && !examIdParam.isEmpty()) {
        try {
            examId = Integer.parseInt(examIdParam);
        } catch (NumberFormatException e) {
            examId = 0;
        }
    }
    
    String courseName = request.getParameter("course_name");
    if (courseName == null) courseName = "";
    
    String dateFilter = request.getParameter("exam_date");
    if (dateFilter == null) dateFilter = "";
    
    // Generate filename based on filters
    String filename = "exam_register";
    if (examId > 0) {
        filename += "_exam" + examId;
    }
    if (!courseName.isEmpty()) {
        filename += "_" + courseName.replaceAll("[^a-zA-Z0-9]", "_");
    }
    if (!dateFilter.isEmpty()) {
        filename += "_" + dateFilter;
    }
    filename += ".xls";
    
    response.setHeader("Content-Disposition", "attachment;filename=" + filename);
%>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        table { border-collapse: collapse; width: 100%; }
        th { background-color: #4CAF50; color: white; padding: 8px; font-weight: bold; }
        td { border: 1px solid #ddd; padding: 8px; }
        tr:nth-child(even) { background-color: #f2f2f2; }
        .header-row { background-color: #2c3e50; color: white; font-size: 16px; }
        .subheader { background-color: #34495e; color: white; padding: 5px; }
    </style>
</head>
<body>
    <h2 style="text-align: center; color: #2c3e50;">Exam Register Report</h2>
    
    <!-- Report Information -->
    <div style="margin-bottom: 20px;">
        <table border="0" style="width: 100%;">
            <tr>
                <td><strong>Generated On:</strong> <%= new java.util.Date() %></td>
                <td><strong>Generated By:</strong> User ID: <%= session.getAttribute("userId") %></td>
            </tr>
            <% if (examId > 0) { %>
            <tr><td colspan="2"><strong>Exam ID:</strong> <%= examId %></td></tr>
            <% } %>
            <% if (!courseName.isEmpty()) { %>
            <tr><td colspan="2"><strong>Course:</strong> <%= courseName %></td></tr>
            <% } %>
            <% if (!dateFilter.isEmpty()) { %>
            <tr><td colspan="2"><strong>Exam Date:</strong> <%= dateFilter %></td></tr>
            <% } %>
        </table>
    </div>
    
    <!-- Data Table -->
    <table border="1">
        <thead>
            <tr class="header-row">
                <th>#</th>
                <th>Student Name</th>
                <th>Student ID</th>
                <th>Course</th>
                <th>Exam ID</th>
                <th>Exam Date</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th>Duration (HH:MM:SS)</th>
                <th>Device Identifier</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
        <%
            try {
                ResultSet rs = null;
                if (examId > 0 || !courseName.isEmpty() || !dateFilter.isEmpty()) {
                    rs = pDAO.getFilteredExamRegister(examId, courseName, dateFilter);
                } else {
                    rs = pDAO.getAllExamRegister();
                }
                
                int count = 0;
                int completedCount = 0;
                int inProgressCount = 0;
                
                if (rs != null) {
                    while (rs.next()) {
                        count++;
                        String firstName = rs.getString("first_name");
                        String lastName = rs.getString("last_name");
                        int studentId = rs.getInt("student_id");
                        String course = rs.getString("course_name");
                        int currentExamId = rs.getInt("exam_id");
                        Date examDate = rs.getDate("exam_date");
                        Time startTime = rs.getTime("start_time");
                        Time endTime = rs.getTime("end_time");
                        String deviceIdentifier = rs.getString("device_identifier");
                        int durationSeconds = rs.getInt("duration_seconds");
                        
                        String studentName = (firstName != null ? firstName : "") + " " + 
                                           (lastName != null ? lastName : "");
                        String duration = "";
                        if (durationSeconds > 0) {
                            int hours = durationSeconds / 3600;
                            int minutes = (durationSeconds % 3600) / 60;
                            int seconds = durationSeconds % 60;
                            duration = String.format("%02d:%02d:%02d", hours, minutes, seconds);
                        }
                        
                        String status = endTime != null ? "Completed" : "In Progress";
                        if (endTime != null) {
                            completedCount++;
                        } else {
                            inProgressCount++;
                        }
        %>
        <tr>
            <td><%= count %></td>
            <td><%= studentName %></td>
            <td><%= studentId %></td>
            <td><%= course %></td>
            <td><%= currentExamId %></td>
            <td><%= examDate != null ? examDate.toString() : "N/A" %></td>
            <td><%= startTime != null ? startTime.toString() : "N/A" %></td>
            <td><%= endTime != null ? endTime.toString() : "N/A" %></td>
            <td><%= duration.isEmpty() ? "N/A" : duration %></td>
            <td><%= deviceIdentifier != null ? deviceIdentifier : "Unknown" %></td>
            <td><%= status %></td>
        </tr>
        <%
                    }
                }
                
                // Add summary row
                if (count > 0) {
        %>
        <tr style="background-color: #ecf0f1; font-weight: bold;">
            <td colspan="3">TOTAL RECORDS: <%= count %></td>
            <td colspan="2">COMPLETED: <%= completedCount %></td>
            <td colspan="2">IN PROGRESS: <%= inProgressCount %></td>
            <td colspan="4">COMPLETION RATE: <%= String.format("%.1f%%", (completedCount * 100.0 / count)) %></td>
        </tr>
        <%
                }
                
            } catch (SQLException e) {
        %>
        <tr>
            <td colspan="11" style="color: red; text-align: center;">
                Error generating report: <%= e.getMessage() %>
            </td>
        </tr>
        <%
            }
        %>
        </tbody>
    </table>
    
    <!-- Footer Information -->
    <div style="margin-top: 30px; font-size: 11px; color: #7f8c8d;">
        <p>Generated by MUT Exam System</p>
        <p>© <%= new java.util.Date().getYear() + 1900 %> Mangosuthu University of Technology</p>
    </div>
</body>
</html>